### ISSUE TITLE
No pre build version?

### ISSUE THREAD

**Issue by kezif** [misprit7/WireHead#4]
If I understood correctly you should manualy build wirehead mod using modloader. Why it so tho? 
Version accessible from the steam menu would decrease hussle

**Comment by misprit7** [comment]
I tried to do this, steam won't let me change visibility to public for some reason. I figure most people who would actually be interesting in using this would likely be comfortable compiling mods, so for now I don't really want to fiddle with steam a bunch.

**Comment by kezif** [comment]
fair enough
