### ISSUE TITLE
Are you open to performance optimization PRs?

### ISSUE THREAD

**Issue by Tacodiva** [misprit7/WireHead#5]
Hey,
I saw your video on this project and thought it was pretty cool. Looking through your code, I can see quite a bit of potential for further optimization. I have some ideas I believe could make this noticably faster, and I'm curious if you're accepting PRs or if you want to keep this in the less optimized but easier to understand state it's in now.

Thanks :)

**Comment by misprit7** [comment]
I'm open to optimizations, although I'm planning a pretty major paradigm shift in how I'm doing things (exporting the world circuitry to llvm, compiling that and running it), so it's possible changes will be obsolete after I do that. Also keep in mind that I have spent quite a while thinking about this, so while there are definitely possible improvements, I doubt there's any super low hanging fruit. 

That being said, if you see something specific you think would be a run time improvement feel free to let me know/implement it, if it is cleanly written and works I'd be happy to merge it.

**Comment by Tacodiva** [comment]
The most obvious improvement to me was that you should not be using C#s builtin 2D arrays for performance sensitive stuff like this. See [this stackoverflow question](https://stackoverflow.com/questions/468832/why-are-multi-dimensional-arrays-in-net-slower-than-normal-arrays) but essentially, they're measurably slower than just using a 1D array and doing the `x * width + y` calculation yourself. If you really wanted to get fancy, you could eliminate all the bounds checking entirely by using unsafe arrays.

I'm very intrigued by the compiling idea. If you're familiar with LLVM and are comfortable linking to and invoking it from C# than you should totally go that way. In my opinion, however, it would be more portable and elegant to compile to CIL. If you use unmanaged memory and CIL, there's basically no difference in performance compared to native code sence it will very probably just gets JITed. The advantages over LLVM being you don't have to package LLVM in complicated cross-platform ways and it's a whole lot easier to access existing C# code.

Anyways sorry for the rant, just think it's a cool project and thought I'd throw my thoughts. I'd be happy to help you work on this if you're interested HMU on Discord.
