### ISSUE TITLE
Instruction / prerequisites to compile this?

### ISSUE THREAD

**Issue by RonSijm** [misprit7/WireHead#6]
Hey there! I saw your project on youtube and it seems really cool! Nice job.

Anyways, I cloned the source code, and tried to compile it.
First time compiling I got:
 > C:\Users\ronsi\Downloads\WireHead-main\WireHead.csproj(3,3): error MSB4019: The imported project "C:\Users\ronsi\Downloads\tModLoader.targets" was not found.

So I figured I needed tModLoader. I cloned tModLoader (/tree/1.4.4) (and changed the import to
>   Import Project="..\tModLoader-1.4.4\tModLoader.targets" 

However after doing that, and I tried to compile, I then got the error:

> C:\Users\ronsi\Downloads\tModLoader-1.4.4\tModLoader.targets(3,3): error MSB4019: The imported project "C:\Users\ronsi\Downloads\tModLoader-1.4.4\src\WorkspaceInfo.targets" was not
found. Confirm that the expression in the Import declaration "src/WorkspaceInfo.targets" is correct

`src/WorkspaceInfo.targets` doesn't seem to exist in the tModLoader folder, so I'm not really sure where to go from here...

Do you have any instructions on what needs to be installed in order to compile this?

**Comment by misprit7** [comment]
This is still on the 1.4.3.6 version of tModLoader, I've been meaning to port it but want to get some features finished and stable first. Probably the easiest way to do this would just do what you already did except use the [1.4.3 branch](https://github.com/tModLoader/tModLoader/tree/1.4.3-legacy), or select 1.4.3-legacy from the steam beta menu.

**Comment by RonSijm** [comment]
Ok thanks! It took a while to get everything to get it to compile, but I managed to get it to compile eventually.

I thought it'd be useful for other people to understand how to compile this, so I wrote some instructions on how to compile this, and PRed it [over here](https://github.com/misprit7/WireHead/pull/7)

You can see the rendered version of the markdown of the readme at my fork: https://github.com/RonSijm/WireHead-CompileInstructions#prerequisites-and-compilation-instructions

**Comment by RussDev7** [comment]
> Ok thanks! It took a while to get everything to get it to compile, but I managed to get it to compile eventually.
> 
> I thought it'd be useful for other people to understand how to compile this, so I wrote some instructions on how to compile this, and PRed it [over here](https://github.com/misprit7/WireHead/pull/7)
> 
> You can see the rendered version of the markdown of the readme at my fork: https://github.com/RonSijm/WireHead-CompileInstructions#prerequisites-and-compilation-instructions

This mod does not seem to work? 

From the code I gathered the following commands:
```
/accel,a preprocess,p
/accel,a sync,s
/accel,a enable,e
/accel,a disable,d
```
![Lamps](https://github.com/misprit7/WireHead/assets/33048298/3b022a00-c3d3-4a8b-912b-d128c5bcae28)
Would be helpful if we could discuss this over discord: dannyruss

**Comment by misprit7** [comment]
It has now been ported along with a bunch of other breaking changes.
